// dprint-ignore-file
import * as cometbft_0_34 from "./cometbft-0-34"
import * as cometbft_0_37 from "./cometbft-0-37"
import * as cometbft_0_38 from "./cometbft-0-38"

export type EmptyResponse = cometbft_0_38.EmptyResponse | cometbft_0_37.EmptyResponse | cometbft_0_34.EmptyResponse
export type ErrorResponse = cometbft_0_38.ErrorResponse | cometbft_0_37.ErrorResponse | cometbft_0_34.ErrorResponse
export type HealthRequest = cometbft_0_38.HealthRequest | cometbft_0_37.HealthRequest | cometbft_0_34.HealthRequest
export type HealthParams = never
export type HealthResponse = cometbft_0_38.HealthResponse | cometbft_0_37.HealthResponse | cometbft_0_34.HealthResponse
export type HealthResult = cometbft_0_38.HealthResult | cometbft_0_37.HealthResult | cometbft_0_34.HealthResult
export type StatusRequest = cometbft_0_38.StatusRequest | cometbft_0_37.StatusRequest | cometbft_0_34.StatusRequest
export type StatusParams = never
export type StatusResponse = cometbft_0_38.StatusResponse | cometbft_0_37.StatusResponse | cometbft_0_34.StatusResponse
export type StatusResult = cometbft_0_38.StatusResult | cometbft_0_37.StatusResult | cometbft_0_34.StatusResult
export type NetInfoRequest = cometbft_0_38.NetInfoRequest | cometbft_0_37.NetInfoRequest | cometbft_0_34.NetInfoRequest
export type NetInfoParams = never
export type NetInfoResponse = cometbft_0_38.NetInfoResponse | cometbft_0_37.NetInfoResponse | cometbft_0_34.NetInfoResponse
export type NetInfoResult = cometbft_0_38.NetInfoResult | cometbft_0_37.NetInfoResult | cometbft_0_34.NetInfoResult
export type BlockchainRequest = cometbft_0_38.BlockchainRequest | cometbft_0_37.BlockchainRequest | cometbft_0_34.BlockchainRequest
export type BlockchainParams = cometbft_0_38.BlockchainParams | cometbft_0_37.BlockchainParams | cometbft_0_34.BlockchainParams
export type BlockchainResponse = cometbft_0_38.BlockchainResponse | cometbft_0_37.BlockchainResponse | cometbft_0_34.BlockchainResponse
export type BlockchainResult = cometbft_0_38.BlockchainResult | cometbft_0_37.BlockchainResult | cometbft_0_34.BlockchainResult
export type HeaderRequest = cometbft_0_38.HeaderRequest | cometbft_0_37.HeaderRequest
export type HeaderParams = cometbft_0_38.HeaderParams | cometbft_0_37.HeaderParams
export type HeaderResponse = cometbft_0_38.HeaderResponse | cometbft_0_37.HeaderResponse
export type HeaderResult = cometbft_0_38.HeaderResult | cometbft_0_37.HeaderResult
export type HeaderByHashRequest = cometbft_0_38.HeaderByHashRequest | cometbft_0_37.HeaderByHashRequest
export type HeaderByHashParams = cometbft_0_38.HeaderByHashParams | cometbft_0_37.HeaderByHashParams
export type HeaderByHashResponse = cometbft_0_38.HeaderByHashResponse | cometbft_0_37.HeaderByHashResponse
export type HeaderByHashResult = cometbft_0_38.HeaderByHashResult | cometbft_0_37.HeaderByHashResult
export type BlockRequest = cometbft_0_38.BlockRequest | cometbft_0_37.BlockRequest | cometbft_0_34.BlockRequest
export type BlockParams = cometbft_0_38.BlockParams | cometbft_0_37.BlockParams | cometbft_0_34.BlockParams
export type BlockResponse = cometbft_0_38.BlockResponse | cometbft_0_37.BlockResponse | cometbft_0_34.BlockResponse
export type BlockResult = cometbft_0_38.BlockResult | cometbft_0_37.BlockResult | cometbft_0_34.BlockResult
export type BlockByHashRequest = cometbft_0_38.BlockByHashRequest | cometbft_0_37.BlockByHashRequest | cometbft_0_34.BlockByHashRequest
export type BlockByHashParams = cometbft_0_38.BlockByHashParams | cometbft_0_37.BlockByHashParams | cometbft_0_34.BlockByHashParams
export type BlockByHashResponse = cometbft_0_38.BlockByHashResponse | cometbft_0_37.BlockByHashResponse | cometbft_0_34.BlockByHashResponse
export type BlockByHashResult = cometbft_0_38.BlockByHashResult | cometbft_0_37.BlockByHashResult | cometbft_0_34.BlockByHashResult
export type BlockResultsRequest = cometbft_0_38.BlockResultsRequest | cometbft_0_37.BlockResultsRequest | cometbft_0_34.BlockResultsRequest
export type BlockResultsParams = cometbft_0_38.BlockResultsParams | cometbft_0_37.BlockResultsParams | cometbft_0_34.BlockResultsParams
export type BlockResultsResponse = cometbft_0_38.BlockResultsResponse | cometbft_0_37.BlockResultsResponse | cometbft_0_34.BlockResultsResponse
export type BlockResultsResult = cometbft_0_38.BlockResultsResult | cometbft_0_37.BlockResultsResult | cometbft_0_34.BlockResultsResult
export type CommitRequest = cometbft_0_38.CommitRequest | cometbft_0_37.CommitRequest | cometbft_0_34.CommitRequest
export type CommitParams = cometbft_0_38.CommitParams | cometbft_0_37.CommitParams | cometbft_0_34.CommitParams
export type CommitResponse = cometbft_0_38.CommitResponse | cometbft_0_37.CommitResponse | cometbft_0_34.CommitResponse
export type CommitResult = cometbft_0_38.CommitResult | cometbft_0_37.CommitResult | cometbft_0_34.CommitResult
export type ValidatorsRequest = cometbft_0_38.ValidatorsRequest | cometbft_0_37.ValidatorsRequest | cometbft_0_34.ValidatorsRequest
export type ValidatorsParams = cometbft_0_38.ValidatorsParams | cometbft_0_37.ValidatorsParams | cometbft_0_34.ValidatorsParams
export type ValidatorsResponse = cometbft_0_38.ValidatorsResponse | cometbft_0_37.ValidatorsResponse | cometbft_0_34.ValidatorsResponse
export type ValidatorsResult = cometbft_0_38.ValidatorsResult | cometbft_0_37.ValidatorsResult | cometbft_0_34.ValidatorsResult
export type GenesisRequest = cometbft_0_38.GenesisRequest | cometbft_0_37.GenesisRequest | cometbft_0_34.GenesisRequest
export type GenesisParams = never
export type GenesisResponse = cometbft_0_38.GenesisResponse | cometbft_0_37.GenesisResponse | cometbft_0_34.GenesisResponse
export type GenesisResult = cometbft_0_38.GenesisResult | cometbft_0_37.GenesisResult | cometbft_0_34.GenesisResult
export type GenesisChunkedRequest = cometbft_0_38.GenesisChunkedRequest | cometbft_0_37.GenesisChunkedRequest | cometbft_0_34.GenesisChunkedRequest
export type GenesisChunkedParams = cometbft_0_38.GenesisChunkedParams | cometbft_0_37.GenesisChunkedParams | cometbft_0_34.GenesisChunkedParams
export type GenesisChunkedResponse = cometbft_0_38.GenesisChunkedResponse | cometbft_0_37.GenesisChunkedResponse | cometbft_0_34.GenesisChunkedResponse
export type GenesisChunkedResult = cometbft_0_38.GenesisChunkedResult | cometbft_0_37.GenesisChunkedResult | cometbft_0_34.GenesisChunkedResult
export type DumpConsensusStateRequest = cometbft_0_38.DumpConsensusStateRequest | cometbft_0_37.DumpConsensusStateRequest | cometbft_0_34.DumpConsensusStateRequest
export type DumpConsensusStateParams = cometbft_0_38.DumpConsensusStateParams | cometbft_0_37.DumpConsensusStateParams | cometbft_0_34.DumpConsensusStateParams
export type DumpConsensusStateResponse = cometbft_0_38.DumpConsensusStateResponse | cometbft_0_37.DumpConsensusStateResponse | cometbft_0_34.DumpConsensusStateResponse
export type DumpConsensusStateResult = cometbft_0_38.DumpConsensusStateResult | cometbft_0_37.DumpConsensusStateResult | cometbft_0_34.DumpConsensusStateResult
export type ConsensusStateRequest = cometbft_0_38.ConsensusStateRequest | cometbft_0_37.ConsensusStateRequest | cometbft_0_34.ConsensusStateRequest
export type ConsensusStateParams = cometbft_0_38.ConsensusStateParams | cometbft_0_37.ConsensusStateParams | cometbft_0_34.ConsensusStateParams
export type ConsensusStateResponse = cometbft_0_38.ConsensusStateResponse | cometbft_0_37.ConsensusStateResponse | cometbft_0_34.ConsensusStateResponse
export type ConsensusStateResult = cometbft_0_38.ConsensusStateResult | cometbft_0_37.ConsensusStateResult | cometbft_0_34.ConsensusStateResult
export type ConsensusParamsRequest = cometbft_0_38.ConsensusParamsRequest | cometbft_0_37.ConsensusParamsRequest | cometbft_0_34.ConsensusParamsRequest
export type ConsensusParamsParams = cometbft_0_38.ConsensusParamsParams | cometbft_0_37.ConsensusParamsParams | cometbft_0_34.ConsensusParamsParams
export type ConsensusParamsResponse = cometbft_0_38.ConsensusParamsResponse | cometbft_0_37.ConsensusParamsResponse | cometbft_0_34.ConsensusParamsResponse
export type ConsensusParamsResult = cometbft_0_38.ConsensusParamsResult | cometbft_0_37.ConsensusParamsResult | cometbft_0_34.ConsensusParamsResult
export type UnconfirmedTxsRequest = cometbft_0_38.UnconfirmedTxsRequest | cometbft_0_37.UnconfirmedTxsRequest | cometbft_0_34.UnconfirmedTxsRequest
export type UnconfirmedTxsParams = cometbft_0_38.UnconfirmedTxsParams | cometbft_0_37.UnconfirmedTxsParams | cometbft_0_34.UnconfirmedTxsParams
export type UnconfirmedTxsResponse = cometbft_0_38.UnconfirmedTxsResponse | cometbft_0_37.UnconfirmedTxsResponse | cometbft_0_34.UnconfirmedTxsResponse
export type UnconfirmedTxsResult = cometbft_0_38.UnconfirmedTxsResult | cometbft_0_37.UnconfirmedTxsResult | cometbft_0_34.UnconfirmedTxsResult
export type NumUnconfirmedTxsRequest = cometbft_0_38.NumUnconfirmedTxsRequest | cometbft_0_37.NumUnconfirmedTxsRequest | cometbft_0_34.NumUnconfirmedTxsRequest
export type NumUnconfirmedTxsParams = never
export type NumUnconfirmedTxsResponse = cometbft_0_38.NumUnconfirmedTxsResponse | cometbft_0_37.NumUnconfirmedTxsResponse | cometbft_0_34.NumUnconfirmedTxsResponse
export type NumUnconfirmedTxsResult = cometbft_0_38.NumUnconfirmedTxsResult | cometbft_0_37.NumUnconfirmedTxsResult | cometbft_0_34.NumUnconfirmedTxsResult
export type TxSearchRequest = cometbft_0_38.TxSearchRequest | cometbft_0_37.TxSearchRequest | cometbft_0_34.TxSearchRequest
export type TxSearchParams = cometbft_0_38.TxSearchParams | cometbft_0_37.TxSearchParams | cometbft_0_34.TxSearchParams
export type TxSearchResponse = cometbft_0_38.TxSearchResponse | cometbft_0_37.TxSearchResponse | cometbft_0_34.TxSearchResponse
export type TxSearchResult = cometbft_0_38.TxSearchResult | cometbft_0_37.TxSearchResult | cometbft_0_34.TxSearchResult
export type BlockSearchRequest = cometbft_0_38.BlockSearchRequest | cometbft_0_37.BlockSearchRequest | cometbft_0_34.BlockSearchRequest
export type BlockSearchParams = cometbft_0_38.BlockSearchParams | cometbft_0_37.BlockSearchParams | cometbft_0_34.BlockSearchParams
export type BlockSearchResponse = cometbft_0_38.BlockSearchResponse | cometbft_0_37.BlockSearchResponse | cometbft_0_34.BlockSearchResponse
export type BlockSearchResult = cometbft_0_38.BlockSearchResult | cometbft_0_37.BlockSearchResult | cometbft_0_34.BlockSearchResult
export type TxRequest = cometbft_0_38.TxRequest | cometbft_0_37.TxRequest | cometbft_0_34.TxRequest
export type TxParams = cometbft_0_38.TxParams | cometbft_0_37.TxParams | cometbft_0_34.TxParams
export type TxResponse = cometbft_0_38.TxResponse | cometbft_0_37.TxResponse | cometbft_0_34.TxResponse
export type TxResult = cometbft_0_38.TxResult | cometbft_0_37.TxResult | cometbft_0_34.TxResult
export type BroadcastEvidenceRequest = cometbft_0_38.BroadcastEvidenceRequest | cometbft_0_37.BroadcastEvidenceRequest | cometbft_0_34.BroadcastEvidenceRequest
export type BroadcastEvidenceParams = cometbft_0_38.BroadcastEvidenceParams | cometbft_0_37.BroadcastEvidenceParams | cometbft_0_34.BroadcastEvidenceParams
export type BroadcastEvidenceResponse = cometbft_0_38.BroadcastEvidenceResponse | cometbft_0_37.BroadcastEvidenceResponse | cometbft_0_34.BroadcastEvidenceResponse
export type BroadcastEvidenceResult = cometbft_0_38.BroadcastEvidenceResult | cometbft_0_37.BroadcastEvidenceResult | cometbft_0_34.BroadcastEvidenceResult
export type BroadcastTxSyncRequest = cometbft_0_38.BroadcastTxSyncRequest | cometbft_0_37.BroadcastTxSyncRequest | cometbft_0_34.BroadcastTxSyncRequest
export type BroadcastTxSyncParams = cometbft_0_38.BroadcastTxSyncParams | cometbft_0_37.BroadcastTxSyncParams | cometbft_0_34.BroadcastTxSyncParams
export type BroadcastTxSyncResponse = cometbft_0_38.BroadcastTxSyncResponse | cometbft_0_37.BroadcastTxSyncResponse | cometbft_0_34.BroadcastTxSyncResponse
export type BroadcastTxSyncResult = cometbft_0_38.BroadcastTxSyncResult | cometbft_0_37.BroadcastTxSyncResult | cometbft_0_34.BroadcastTxSyncResult
export type BroadcastTxAsyncRequest = cometbft_0_38.BroadcastTxAsyncRequest | cometbft_0_37.BroadcastTxAsyncRequest | cometbft_0_34.BroadcastTxAsyncRequest
export type BroadcastTxAsyncParams = cometbft_0_38.BroadcastTxAsyncParams | cometbft_0_37.BroadcastTxAsyncParams | cometbft_0_34.BroadcastTxAsyncParams
export type BroadcastTxAsyncResponse = cometbft_0_38.BroadcastTxAsyncResponse | cometbft_0_37.BroadcastTxAsyncResponse | cometbft_0_34.BroadcastTxAsyncResponse
export type BroadcastTxAsyncResult = cometbft_0_38.BroadcastTxAsyncResult | cometbft_0_37.BroadcastTxAsyncResult | cometbft_0_34.BroadcastTxAsyncResult
export type BroadcastTxCommitRequest = cometbft_0_38.BroadcastTxCommitRequest | cometbft_0_37.BroadcastTxCommitRequest | cometbft_0_34.BroadcastTxCommitRequest
export type BroadcastTxCommitParams = cometbft_0_38.BroadcastTxCommitParams | cometbft_0_37.BroadcastTxCommitParams | cometbft_0_34.BroadcastTxCommitParams
export type BroadcastTxCommitResponse = cometbft_0_38.BroadcastTxCommitResponse | cometbft_0_37.BroadcastTxCommitResponse | cometbft_0_34.BroadcastTxCommitResponse
export type BroadcastTxCommitResult = cometbft_0_38.BroadcastTxCommitResult | cometbft_0_37.BroadcastTxCommitResult | cometbft_0_34.BroadcastTxCommitResult
export type CheckTxRequest = cometbft_0_38.CheckTxRequest | cometbft_0_37.CheckTxRequest | cometbft_0_34.CheckTxRequest
export type CheckTxParams = cometbft_0_38.CheckTxParams | cometbft_0_37.CheckTxParams | cometbft_0_34.CheckTxParams
export type CheckTxResponse = cometbft_0_38.CheckTxResponse | cometbft_0_37.CheckTxResponse | cometbft_0_34.CheckTxResponse
export type CheckTxResult = cometbft_0_38.CheckTxResult | cometbft_0_37.CheckTxResult | cometbft_0_34.CheckTxResult
export type AbciInfoRequest = cometbft_0_38.AbciInfoRequest | cometbft_0_37.AbciInfoRequest | cometbft_0_34.AbciInfoRequest
export type AbciInfoParams = cometbft_0_38.AbciInfoParams | cometbft_0_37.AbciInfoParams | cometbft_0_34.AbciInfoParams
export type AbciInfoResponse = cometbft_0_38.AbciInfoResponse | cometbft_0_37.AbciInfoResponse | cometbft_0_34.AbciInfoResponse
export type AbciInfoResult = cometbft_0_38.AbciInfoResult | cometbft_0_37.AbciInfoResult | cometbft_0_34.AbciInfoResult
export type AbciQueryRequest = cometbft_0_38.AbciQueryRequest | cometbft_0_37.AbciQueryRequest | cometbft_0_34.AbciQueryRequest
export type AbciQueryParams = cometbft_0_38.AbciQueryParams | cometbft_0_37.AbciQueryParams | cometbft_0_34.AbciQueryParams
export type AbciQueryResponse = cometbft_0_38.AbciQueryResponse | cometbft_0_37.AbciQueryResponse | cometbft_0_34.AbciQueryResponse
export type AbciQueryResult = cometbft_0_38.AbciQueryResult | cometbft_0_37.AbciQueryResult | cometbft_0_34.AbciQueryResult
